using System.Threading;
using Bogus;
using EfCoreLab.Data;
using Microsoft.EntityFrameworkCore;

namespace EfCoreLab
{
    /// <summary>
    /// Provides fake data generation using the Bogus library for testing and development.
    /// Generates realistic customer, invoice, and phone number data with globally unique IDs.
    /// </summary>
    public static class BogusDataGenerator
    {
        /// <summary>
        /// Seeds the database with fake data. Creates customers with invoices and phone numbers.
        /// </summary>
        /// <param name="context">The database context to seed</param>
        /// <param name="customerCount">Number of customers to create</param>
        /// <param name="minInvoicesPerCustomer">Minimum invoices per customer</param>
        /// <param name="maxInvoicesPerCustomer">Maximum invoices per customer</param>
        /// <param name="minPhoneNumbersPerCustomer">Minimum phone numbers per customer</param>
        /// <param name="maxPhoneNumbersPerCustomer">Maximum phone numbers per customer</param>
        public static async Task SeedDatabase(
            AppDbContext context,
            int customerCount = 50,
            int minInvoicesPerCustomer = 1,
            int maxInvoicesPerCustomer = 5,
            int minPhoneNumbersPerCustomer = 1,
            int maxPhoneNumbersPerCustomer = 3)
        {
            // Check if database already has data
            var existingCustomerCount = await context.Customers.CountAsync();
            if (existingCustomerCount > 0)
            {
                Console.WriteLine($"Database already contains {existingCustomerCount} customers. Skipping seed.");
                return;
            }

            Console.WriteLine($"Database is empty. Starting seed process...");
            Console.WriteLine($"Generating {customerCount} customers with invoices and phone numbers...");

            var random = new Random();

            // Generate and save customers first to get their database-generated IDs
            var customers = SeedCustomer(customerCount);
            await context.Customers.AddRangeAsync(customers);
            await context.SaveChangesAsync(); // Save to get IDs

            Console.WriteLine($"✓ Created {customers.Count} customers");

            var allInvoices = new List<Invoice>();
            var allPhoneNumbers = new List<TelephoneNumber>();

            foreach (var customer in customers)
            {
                // Generate random number of invoices for this customer
                int invoiceCount = random.Next(minInvoicesPerCustomer, maxInvoicesPerCustomer + 1);
                var invoices = GenerateInvoices(customer.Id, invoiceCount);
                allInvoices.AddRange(invoices);

                // Generate random number of phone numbers for this customer
                int phoneCount = random.Next(minPhoneNumbersPerCustomer, maxPhoneNumbersPerCustomer + 1);
                var phoneNumbers = GeneratePhoneNumbers(customer.Id, phoneCount);
                allPhoneNumbers.AddRange(phoneNumbers);
            }

            Console.WriteLine($"✓ Generated {allInvoices.Count} invoices");
            Console.WriteLine($"✓ Generated {allPhoneNumbers.Count} phone numbers");

            // Add all invoices and phone numbers
            await context.Invoices.AddRangeAsync(allInvoices);
            await context.TelephoneNumbers.AddRangeAsync(allPhoneNumbers);

            // Save changes
            await context.SaveChangesAsync();

            Console.WriteLine($"");
            Console.WriteLine($"✓ Database seeded successfully!");
            Console.WriteLine($"  Total: {customers.Count} customers, {allInvoices.Count} invoices, {allPhoneNumbers.Count} phone numbers");
        }

        /// <summary>
        /// Generates a list of fake customers with realistic company names and email addresses.
        /// IDs will be auto-generated by the database.
        /// </summary>
        /// <param name="count">The number of customers to generate</param>
        /// <returns>A list of Customer objects with generated data</returns>
        public static List<Customer> SeedCustomer(int count)
        {
            Faker<Customer> faker = new Faker<Customer>("en_GB")
                .CustomInstantiator(f => new Customer
                {
                    Name = f.Company.CompanyName(),
                    Email = f.Internet.Email()
                });

            List<Customer> list = [];
            for (int i = 0; i < count; i++)
            {
                list.Add(faker.Generate());
            }

            return list;
        }

        /// <summary>
        /// Generates a list of fake invoices for a specific customer.
        /// Invoice IDs will be auto-generated by the database.
        /// Generates invoices with random amounts between 10 and 5000, dated within the past 2 years.
        /// </summary>
        /// <param name="custId">The customer ID to associate with the generated invoices</param>
        /// <param name="count">The number of invoices to generate</param>
        /// <returns>A list of Invoice objects with generated data</returns>
        public static List<Invoice> GenerateInvoices(long custId, int count)
        {
            Faker<Invoice> faker = new Faker<Invoice>("en_GB")
                .CustomInstantiator(f =>
                {
                    string invoiceNumber = "INV-" + f.Random.AlphaNumeric(8).ToUpper();
                    DateTime invoiceDate = f.Date.Past(2);
                    decimal amount = f.Finance.Amount(10, 5000);

                    Invoice? invoice = new()
                    {
                        InvoiceNumber = invoiceNumber,
                        InvoiceDate = invoiceDate,
                        Amount = amount,
                        CustomerId = custId
                    };

                    return invoice;
                });

            List<Invoice> list = [];
            for (int i = 0; i < count; i++)
            {
                list.Add(faker.Generate());
            }

            return list;
        }

        // Valid phone number types for random selection
        private static readonly string[] NumberTypes = new[] { "DirectDial", "Work", "Mobile" };
        private static readonly List<string> MobilePrefixes = new() { "071", "072", "073", "074", "075", "076", "077", "078", "079" };
        private static readonly List<string> landLinePrefix = new()
        {
            "+44 20",   // London
            "+44 121",  // Birmingham
            "+44 131",  // Edinburgh
            "+44 141",  // Glasgow
            "+44 151",  // Liverpool
            "+44 161",  // Manchester
            "+44 191"   // Tyneside
        };

        /// <summary>
        /// Generates a list of fake phone numbers for a specific customer.
        /// Phone number IDs will be auto-generated by the database.
        /// Generates UK-formatted phone numbers with random types (Mobile, DirectDial, or Work).
        /// </summary>
        /// <param name="custId">The customer ID to associate with the generated phone numbers</param>
        /// <param name="count">The number of phone numbers to generate</param>
        /// <returns>A list of TelephoneNumber objects with generated data</returns>
        public static List<TelephoneNumber> GeneratePhoneNumbers(long custId, int count)
        {
            Faker<TelephoneNumber> fakerphone = new Faker<TelephoneNumber>("en_GB")
                .CustomInstantiator(f => new TelephoneNumber
                {
                    CustomerId = custId,
                    Number = f.Phone.PhoneNumber(),
                    Type = f.PickRandom(NumberTypes)
                });
            List<TelephoneNumber> listPhone = [];
            for (int i = 0; i < count; i++)
            {
                listPhone.Add(fakerphone.Generate());
            }
            return listPhone;
        }
    }
}
