// File: Domain/Customer.cs
// Suggested folder: Domain
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EfCoreLab.Data
{
    public class Customer
    {
        /// <summary>
        /// Unique identifier for the customer. Auto-generated by the database. 
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        /// <summary>
        /// Customer's name (typically a company name).
        /// </summary>
        public string? Name { get; set; }

        /// <summary>
        /// Customer's email address.
        /// </summary>
        public string? Email { get; set; }

        /// <summary>
        /// Collection of invoices associated with this customer.
        /// </summary>
        public List<Invoice>? Invoices { get; set; } = new List<Invoice>();

        /// <summary>
        /// Calculated property that returns the sum of all invoice amounts for this customer.
        /// Returns 0 if there are no invoices.
        /// </summary>
        public decimal Balance => Invoices?.Sum(i => i.Amount) ?? 0;

        /// <summary>
        /// Collection of phone numbers associated with this customer.
        /// </summary>
        public List<TelephoneNumber>? PhoneNumbers { get; set; } = new List<TelephoneNumber>();
    }
}
