// File: Domain/Invoice.cs
// Suggested folder: Domain
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace EfCoreLab.Data
{
    public class Invoice
    {
        /// <summary>
        /// Unique identifier for the invoice. Auto-generated by the database and globally unique.
        /// </summary>
        [DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public long Id { get; set; }

        /// <summary>
        /// User-provided invoice number. Must start with "INV" and be unique across all customers.
        /// Example: "INV-12345678"
        /// </summary>
        [Required(ErrorMessage = "InvoiceNumber is required.")]
        [RegularExpression(@"^INV.*", ErrorMessage = "InvoiceNumber must start with 'INV'.")]
        public string InvoiceNumber { get; set; } = string.Empty;

        /// <summary>
        /// Foreign key reference to the Customer who owns this invoice.
        /// </summary>
        [Range(1, long.MaxValue, ErrorMessage = "CustomerId must be greater than zero.")]
        public long CustomerId { get; set; }

        /// <summary>
        /// The date the invoice was issued.
        /// </summary>
        public DateTime InvoiceDate { get; set; }

        /// <summary>
        /// The monetary amount of the invoice.
        /// </summary>
        [Column(TypeName = "decimal(18,2)")]
        public decimal Amount { get; set; }

        /// <summary>
        /// Initializes a new instance of the Invoice class.
        /// </summary>
        public Invoice() { }
    }

}
